name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Lint
        run: ruff .
      - name: Test
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: PYTHONPATH=. pytest --cov=trainer_bot --cov-report=xml --cov-report=term --cov-fail-under=70
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/trainer-bot-backend:latest
